### ISSUE TITLE
Checklist - Mihyun

### ISSUE THREAD

**Issue by MKIM1008** [colouring-cities/colouring-britain#338]
- [ ] Construction of demolition (Digital Twin)
- [ ] Retrofit (Energy)
- [ ] Loughborough classification (Land Use)
- [ ] Updated NNDR (Land Use)
